apiVersion: v1
kind: Service
metadata:
  name: gilbian-os-information
spec:
  selector:
    app: gilbian-os-information
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
  type: NodePort
